fix cloudsmith-upload.sh.in path

diff --git a/cmake/in-files/cloudsmith-upload.sh.in b/cmake/in-files/cloudsmith-upload.sh.in
--- a/cmake/in-files/cloudsmith-upload.sh.in
+++ b/cmake/in-files/cloudsmith-upload.sh.in
@@ -1,17 +1,14 @@
 #!/usr/bin/env bash
 
 #
-# Upload the .tar.gz and .xml artifacts to cloudsmith
+# Upload the .tar.gz and .xml artifacts to Cloudsmith
 #
-# Builds are uploaded to one of PROD, BETA or ALPHA repositories
-# The repository depends on the branch and use of tag to determine which repo.
-# ALPHA: Non-master branch no tag
-# BETA: Non-master branch with annotated tag
-# BETA: Master branch no tag
-# PROD: Master branch with annotated tag
+# Repository selection:
+#   ALPHA: Non-master branch, no tag
+#   BETA:  Non-master branch with tag OR master branch without tag
+#   PROD:  Master branch with tag
 #
-# If this script is used on CIRCLECI, TRAVIS or APPVEYOR it will upload the correct files to the chosen repository
-# If this script is used locally it will build the correct artifacts but will not do the upload
+# Local builds generate artifacts but do not upload.
 #
 
 set -xe
@@ -22,28 +19,31 @@ ALPHA_REPO=${CLOUDSMITH_ALPHA_REPO:-'@CLOUDSMITH_USER@/@CLOUDSMITH_BASE_REPOSITO
 
 LOCAL_BUILD=false
 
+# -----------------------------
+# CI environment detection
+# -----------------------------
 if [ "$CIRCLECI" ]; then
     BUILD_ID=${CIRCLE_BUILD_NUM:-1}
-    BUILD_DIR=$HOME/project/build
+    BUILD_DIR=${BUILD_DIR:-"$HOME/project/build"}
     BUILD_BRANCH=$CIRCLE_BRANCH
     BUILD_TAG=$CIRCLE_TAG
     PKG_EXT=${CLOUDSMITH_PKG_EXT:-'deb'}
+
 elif [ "$TRAVIS" ]; then
     BUILD_ID=${TRAVIS_BUILD_NUM:-1}
     BUILD_DIR=$TRAVIS_BUILD_DIR/build
     BUILD_BRANCH=$TRAVIS_BRANCH
     BUILD_TAG=$TRAVIS_TAG
-    if [ "$BUILD_BRANCH" = "$BUILD_TAG" ]; then
-        # Travis makes BUILD_BRANCH = BUILD_TAG so make BUILD_BRANCH ""
-        BUILD_BRANCH=""
-    fi
+    [ "$BUILD_BRANCH" = "$BUILD_TAG" ] && BUILD_BRANCH=""
     PKG_EXT=${CLOUDSMITH_PKG_EXT:-'deb'}
+
 elif [ "$APPVEYOR" ]; then
     BUILD_ID=${APPVEYOR_BUILD_NUMBER:-1}
     BUILD_DIR=$(pwd)
     BUILD_BRANCH=$APPVEYOR_REPO_BRANCH
     BUILD_TAG=$APPVEYOR_REPO_TAG_NAME
     PKG_EXT=${CLOUDSMITH_PKG_EXT:-'exe'}
+
 else
     BUILD_ID=${CIRCLE_BUILD_NUM:-1}
     BUILD_DIR=.
@@ -53,212 +53,189 @@ else
     LOCAL_BUILD=true
 fi
 
+# -----------------------------
+# API key check
+# -----------------------------
 set +x
 if [ -z "$CLOUDSMITH_API_KEY" ] && [ "$LOCAL_BUILD" = "false" ]; then
-    echo 'Cannot deploy to cloudsmith, missing $CLOUDSMITH_API_KEY'
+    echo 'Cannot deploy to Cloudsmith: missing $CLOUDSMITH_API_KEY'
     exit 0
 fi
 set -x
 
+# -----------------------------
+# Install cloudsmith-cli (PEP-668 compliant)
+# -----------------------------
+install_cloudsmith_cli() {
+    if command -v pipx >/dev/null 2>&1; then
+        pipx install cloudsmith-cli
+        return
+    fi
+
+    if command -v apt-get >/dev/null 2>&1; then
+        sudo apt-get update
+        sudo apt-get install -y pipx python3-venv
+        pipx ensurepath
+        pipx install cloudsmith-cli
+        return
+    fi
+
+    if command -v dnf >/dev/null 2>&1; then
+        sudo dnf install -y pipx python3-virtualenv
+        pipx ensurepath
+        pipx install cloudsmith-cli
+        return
+    fi
+
+    if command -v brew >/dev/null 2>&1; then
+        brew install pipx
+        pipx ensurepath
+        pipx install cloudsmith-cli
+        return
+    fi
+
+    echo "ERROR: pipx not available and no supported package manager found."
+    exit 1
+}
+
 if [ "$CIRCLECI" ] || [ "$TRAVIS" ]; then
     if [ "$DEPLOY_USE_ORB" != "true" ]; then
-        if pyenv versions 2>&1 >/dev/null; then
-          pyenv versions
-          version_1=$(python --version | cut -d '.' -f1 | cut -d ' ' -f2)
-          version_2=$(python --version | cut -d '.' -f2)
-          if [ $version_1 -lt 3 ] || [ $version_2 -lt 5 ]; then
-            sudo apt install software-properties-common
-            sudo apt update
-            sudo apt install -y python3.8 python3-pip
-            sudo rm /usr/bin/python3
-            sudo ln -s /usr/bin/python3.8 /usr/bin/python3
-          fi
-          python3 --version
-          sudo python3 -m pip install cloudsmith-cli
-          pyenv rehash
-        elif test -d $HOME/cs-venv; then
-            source $HOME/cs-venv/bin/activate
-            python -m pip install cloudsmith-cli
-        elif dnf --version 2>&1 >/dev/null; then
-            sudo dnf -y install python3-pip python3-setuptools
-            sudo python3 -m pip install -q cloudsmith-cli
-        elif apt-get --version 2>&1 >/dev/null; then
-            COUNTER=0
-            sudo apt install software-properties-common
-            sudo apt update
-            sudo apt install -y python3.8
-            sudo rm /usr/bin/python3
-            sudo ln -s /usr/bin/python3.8 /usr/bin/python3
-            until
-                sudo apt-get install python3-pip python3-setuptools
-            do
-                if [ "$COUNTER" -gt  "20" ]; then
-                    exit -1
-                fi
-                sleep 5
-                ((COUNTER++))
-            done
-            sudo python3 -m pip install --upgrade pip
-            sudo python3 -m pip install -q cloudsmith-cli
-        fi
+        install_cloudsmith_cli
     fi
 fi
 
-commit=$(git rev-parse --short=7 HEAD) || commit="unknown"
-tag=$(git tag --contains HEAD)
+# -----------------------------
+# Build metadata
+# -----------------------------
+commit=$(git rev-parse --short=7 HEAD || echo "unknown")
+tag=$(git tag --contains HEAD || true)
 
-ls -la
-pwd
-xml=$(ls $BUILD_DIR/*.xml)
-cat $xml
-tarball=$(ls $BUILD_DIR/*.tar.gz)
+xml=$(ls "$BUILD_DIR"/*.xml)
+tarball=$(ls "$BUILD_DIR"/*.tar.gz)
 tarball_basename=${tarball##*/}
-echo $tarball
-echo $tarball_basename
 
-source $BUILD_DIR/pkg_version.sh
+source "$BUILD_DIR/pkg_version.sh"
+
 if [ -n "${OCPN_TARGET}" ]; then
-    tarball_name=@PACKAGE_NAME@-@PACKAGE_VERSION@-${PKG_TARGET}-@COMPOUND_ARCH_DASH@@PKG_TARGET_WX_VER@@PKG_BUILD_GTK@-${PKG_TARGET_VERSION}-${OCPN_TARGET}-tarball
+    tarball_name="@PACKAGE_NAME@-@PACKAGE_VERSION@-${PKG_TARGET}-@COMPOUND_ARCH_DASH@@PKG_TARGET_WX_VER@@PKG_BUILD_GTK@-${PKG_TARGET_VERSION}-${OCPN_TARGET}-tarball"
 else
-    tarball_name=@PACKAGE_NAME@-@PACKAGE_VERSION@-${PKG_TARGET}-@COMPOUND_ARCH_DASH@@PKG_TARGET_WX_VER@@PKG_BUILD_GTK@-${PKG_TARGET_VERSION}-tarball
+    tarball_name="@PACKAGE_NAME@-@PACKAGE_VERSION@-${PKG_TARGET}-@COMPOUND_ARCH_DASH@@PKG_TARGET_WX_VER@@PKG_BUILD_GTK@-${PKG_TARGET_VERSION}-tarball"
 fi
 
-if [ "$(ls $BUILD_DIR/*.${PKG_EXT})" ]; then
-    pkg=$(ls $BUILD_DIR/*.${PKG_EXT})
-else
-    pkg=""
-fi
+pkg=$(ls "$BUILD_DIR"/*.${PKG_EXT} 2>/dev/null || echo "")
 
-echo $BUILD_BRANCH
-echo $BUILD_TAG
-echo ${#BUILD_TAG}
-if [ "$BUILD_TAG" = "" ] && [ "$tag" != "" ]; then
+# -----------------------------
+# Branch/tag → repo selection
+# -----------------------------
+echo "$BUILD_BRANCH"
+echo "$BUILD_TAG"
+
+if [ -z "$BUILD_TAG" ] && [ -n "$tag" ]; then
     BUILD_TAG=$tag
-    echo "Build tag: $BUILD_TAG"
-fi
-if [ "$BUILD_BRANCH" = "" ]; then
-    build_commit=$(git show -s --format=%d $BUILD_TAG)
-    is_master=$(echo $build_commit | awk '/\/master/ {print}')
-    if [ "$is_master" != "" ] || [ "$TRAVIS" ]; then
-        BUILD_BRANCH="master"
-    fi
 fi
 
-BUILD_BRANCH_LOWER=`echo $BUILD_BRANCH | tr '[A-Z]' '[a-z]'`
+if [ -z "$BUILD_BRANCH" ]; then
+    build_commit=$(git show -s --format=%d "$BUILD_TAG")
+    is_master=$(echo "$build_commit" | awk '/\/master/ {print}')
+    [ -n "$is_master" ] && BUILD_BRANCH="master"
+fi
+
+BUILD_BRANCH_LOWER=$(echo "$BUILD_BRANCH" | tr 'A-Z' 'a-z')
+
 if [ "$BUILD_BRANCH_LOWER" = "master" ]; then
-    echo "In master branch "
-    if [ -n "$BUILD_TAG"  ]; then
-        echo "building with tag"
+    if [ -n "$BUILD_TAG" ]; then
         VERSION=$BUILD_TAG
         REPO="$PROD_REPO"
     else
         VERSION="@PROJECT_VERSION@+${BUILD_ID}.${commit}"
-        echo "building without tag"
         REPO="$BETA_REPO"
     fi
 else
-    echo "In non master branch " $BUILD_BRANCH
     if [ -n "$BUILD_TAG" ]; then
-        echo "building with tag"
         VERSION=$BUILD_TAG
         REPO="$BETA_REPO"
     else
-        echo "building without tag"
         VERSION="@PROJECT_VERSION@+${BUILD_ID}.${commit}"
         REPO="$ALPHA_REPO"
     fi
 fi
-echo $VERSION
-echo $REPO
 
-if [ "$APPVEYOR" ] || [ $LOCAL_BUILD=true ]; then
-    echo 'substituting xml file variables for windows build'
-    while read line; do
+echo "$VERSION"
+echo "$REPO"
+
+# -----------------------------
+# Substitute metadata variables
+# -----------------------------
+if [ "$APPVEYOR" ] || [ "$LOCAL_BUILD" = true ]; then
+    while read -r line; do
         line=${line//--pkg_repo--/$REPO}
         line=${line//--name--/$tarball_name}
         line=${line//--version--/$VERSION}
         line=${line//--filename--/$tarball_basename}
-        echo $line
-    done < "$xml" > xml.tmp && cat xml.tmp && cp xml.tmp $xml && rm xml.tmp
+        echo "$line"
+    done < "$xml" > xml.tmp
+    cp xml.tmp "$xml"
+    rm xml.tmp
 else
-    echo 'substituting xml file variables for non-windows build'
-    sudo sed -i -e "s|--pkg_repo--|$REPO|"  $xml
-    sudo sed -i -e "s|--name--|$tarball_name|" $xml
-    sudo sed -i -e "s|--version--|$VERSION|" $xml
-    sudo sed -i -e "s|--filename--|$tarball_basename|" $xml
+    sudo sed -i -e "s|--pkg_repo--|$REPO|" "$xml"
+    sudo sed -i -e "s|--name--|$tarball_name|" "$xml"
+    sudo sed -i -e "s|--version--|$VERSION|" "$xml"
+    sudo sed -i -e "s|--filename--|$tarball_basename|" "$xml"
 fi
 
-cat $xml
-ls -l $BUILD_DIR
-cur_dir=$(pwd)
-gunzip -f $tarball
+# -----------------------------
+# Rebuild tarball with metadata
+# -----------------------------
+gunzip -f "$tarball"
 cd "$BUILD_DIR"
 rm -f metadata.xml
 tarball_tar=$(ls *.tar)
 xml_here=$(ls *.xml)
-cp -f $xml_here metadata.xml
-if [ "$TRAVIS" ] || [ "$CIRCLECI" ] || [ ! -z ${LOCAL_DEPLOY+x} ]; then
-    mkdir build_tar
-    cp $tarball_tar build_tar/.
-    cd build_tar
-    tar -xf $tarball_tar
-    rm *.tar
-    rm -rf root
-    cp ../metadata.xml .
-    tar -cf build_tarfile.tar *
-    tar -tf build_tarfile.tar
-    rm ../$tarball_tar
-    cp build_tarfile.tar ../$tarball_tar
-    cd ..
-    rm -rf build_tar
-else
-    tar -rf $tarball_tar metadata.xml
-fi
-tar -tf $tarball_tar
-gzip -f $tarball_tar
-pwd
+cp -f "$xml_here" metadata.xml
+
+mkdir build_tar
+cp "$tarball_tar" build_tar/
+cd build_tar
+tar -xf "$tarball_tar"
+rm *.tar
+rm -rf root
+cp ../metadata.xml .
+tar -cf build_tarfile.tar *
+cp build_tarfile.tar ../"$tarball_tar"
+cd ..
+rm -rf build_tar
+
+gzip -f "$tarball_tar"
+
 cd "$cur_dir"
-pwd
-ls -la
-ls -la ~/.
 
-# Find if file exists in directory
-function have_any() {
-    [ $# -gt 0 ]
-}
+# -----------------------------
+# Upload to Cloudsmith
+# -----------------------------
+have_any() { [ $# -gt 0 ]; }
 
-if [ ! -z ${LOCAL_DEPLOY+x} ]; then
-    if [ -d "/home/circleci/circleci-output" ]; then
-        sudo cp build/*.gz ~/circleci-output
-        if have_any ./build/*.deb; then
-            sudo cp ./build/*.deb ~/circleci-output
-        elif have_any ./build/*.exe; then
-            sudo cp ./build/*.exe ~/circleci-output
-        fi
-    else
-        echo "Directory ~/circleci-output not found"
-    fi
-elif [ $LOCAL_BUILD = false ]; then
-# Only upload if the owner did the pull request or a member of $COLLABORATORS.
-    if [ "$CIRCLE_PROJECT_USERNAME" = "$CIRCLE_USERNAME" ] || [[ -n "${collab_users+1}"  && ! -z ${CIRCLE_USERNAME}  && "$collab_users" =~ "$git_user" ]]; then
+if [ "$LOCAL_BUILD" = false ]; then
+    if [ "$CIRCLE_PROJECT_USERNAME" = "$CIRCLE_USERNAME" ] || \
+       [[ -n "${collab_users+1}" && -n "$CIRCLE_USERNAME" && "$collab_users" =~ "$git_user" ]]; then
+
         cloudsmith push raw --republish --no-wait-for-sync \
             --name @PACKAGE_NAME@-@PACKAGE_VERSION@-@PKG_TARGET@-@COMPOUND_ARCH_DASH@@PKG_TARGET_WX_VER@@PKG_BUILD_GTK@-@PKG_TARGET_VERSION@-${OCPN_TARGET}-metadata \
-            --version ${VERSION} \
+            --version "$VERSION" \
             --summary "@PACKAGE@ opencpn plugin metadata for automatic installation" \
-            $REPO $xml
+            "$REPO" "$xml"
 
         cloudsmith push raw --republish --no-wait-for-sync \
-            --name $tarball_name \
-            --version ${VERSION} \
+            --name "$tarball_name" \
+            --version "$VERSION" \
             --summary "@PACKAGE@ opencpn plugin tarball for automatic installation" \
-            $REPO $tarball
+            "$REPO" "$tarball"
 
-        if [ "${PKG_EXT}" != "gz" ] && [ "$pkg" != "" ]; then
+        if [ "$PKG_EXT" != "gz" ] && [ -n "$pkg" ]; then
             cloudsmith push raw --republish --no-wait-for-sync \
                 --name opencpn-package-@PACKAGE@-@PACKAGE_VERSION@-@PKG_TARGET@-@COMPOUND_ARCH_DASH@@PKG_TARGET_WX_VER@@PKG_BUILD_GTK@-@PKG_TARGET_VERSION@-${OCPN_TARGET}.${PKG_EXT} \
-                --version ${VERSION} \
+                --version "$VERSION" \
                 --summary "@PACKAGE@ .${PKG_EXT} installation package" \
-                $REPO $pkg
+                "$REPO" "$pkg"
         fi
     fi
 fi
